import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Top Banner
    'banner.worldwideShipping': '🌍 Worldwide Shipping Available',
    'banner.authenticProducts': '✓ 100% Authentic Products',
    'banner.freeShipping': '📦 Free Shipping on Orders Over €100',

    // Navbar
    'nav.home': 'Home',
    'nav.newArrivals': 'New Arrivals',
    'nav.shirts': 'Shirts',
    'nav.clubs': 'Clubs',
    'nav.nationalTeams': 'National Teams',
    'nav.scarves': 'Scarves',
    'nav.balls': 'Balls',
    'nav.bags': 'Bags',
    'nav.promotion': 'Promotion',
    'nav.namesetPatches': 'Nameset & Patches',
    'nav.searchPlaceholder': 'Search jerseys...',
    'nav.accessories': 'Accessories',
    'nav.equipment': 'Equipment',
    
    // Home page
    'home.hero.title': 'Official Football Jerseys',
    'home.hero.subtitle': 'Authentic shirts from your favorite teams and nations. Premium quality with worldwide shipping.',
    'home.hero.shopNow': 'Shop Now',
    'home.hero.nationalTeams': 'National Teams',
    'home.newArrivals': 'New Arrivals',
    'home.new': 'New',
    'home.viewAllNew': 'View All New Arrivals',
    'home.shopByLeague': 'Shop By League',
    'home.featuredJerseys': 'Featured Jerseys',
    'home.viewAllProducts': 'View All Products',
    'home.newsletter.title': 'Join our Newsletter',
    'home.newsletter.subtitle': 'Subscribe to get special offers, free giveaways, and new arrivals notifications.',
    'home.newsletter.placeholder': 'Your email address',
    'home.newsletter.subscribe': 'Subscribe',
    
    // Categories
    'category.nationalTeams': 'National Teams',
    'category.premierLeague': 'Premier League',
    'category.laLiga': 'La Liga',
    'category.serieA': 'Serie A',
    'category.bundesliga': 'Bundesliga',
    'category.ligue1': 'Ligue 1',
    
    // Catalog
    'catalog.filters': 'Filters',
    'catalog.clearAll': 'Clear All',
    'catalog.categories': 'Categories',
    'catalog.sort': 'Sort By',
    'catalog.sort.newest': 'Newest First',
    'catalog.sort.oldest': 'Oldest First',
    'catalog.sort.priceAsc': 'Price: Low to High',
    'catalog.sort.priceDesc': 'Price: High to Low',
    'catalog.sort.seasonDesc': 'Season: Newest to Oldest',
    'catalog.sort.seasonAsc': 'Season: Oldest to Newest',
    'catalog.price': 'Price Range',
    'catalog.price.min': 'Min Price',
    'catalog.price.max': 'Max Price',
    'catalog.brand': 'Brand',
    'catalog.competition': 'Competition',
    'catalog.kitType': 'Kit Type',
    'catalog.condition': 'Condition',
    'catalog.customization': 'Customization',
    'catalog.customization.all': 'All Items',
    'catalog.customization.withNameset': 'With Nameset',
    'catalog.customization.withoutNameset': 'Without Nameset',
    'catalog.format': 'Jersey Format',
    'catalog.format.all': 'All Formats',
    'catalog.format.stadium': 'Stadium Version',
    'catalog.format.playerIssue': 'Player Issue',
    'catalog.format.proStock': 'Pro Stock',
    'catalog.format.matchWorn': 'Match Worn',
    'catalog.format.matchPrepared': 'Match Prepared',
    'catalog.size': 'Size',
    'catalog.applyFilters': 'Apply Filters',
    'catalog.allProducts': 'All Products',
    'catalog.searchResults': 'Search results for',
    'catalog.productsFound': 'products found',
    'catalog.productFound': 'product found',
    'catalog.hideFilters': 'Hide Filters',
    'catalog.showFilters': 'Show Filters',
    'catalog.searchPlaceholder': 'Search products...',
    'catalog.search': 'Search',
    'catalog.noProducts': 'No products found',
    'catalog.noProductsDesc': 'Try adjusting your search or filter to find what you\'re looking for.',
    'catalog.clearFilters': 'Clear Filters',
    
    // Social
    'social.whatsapp': 'Contact us on WhatsApp',
    'social.instagram': 'Follow us on Instagram',

    // Payment
    'payment.acceptedMethods': 'Accepted payment methods',

    // Product card
    'product.customizable': 'Customizable',
    'product.viewDetails': 'View Details',

    // Product detail
    'product.notFound': 'Product Not Found',
    'product.notFoundDesc': 'Sorry, the product you\'re looking for doesn\'t exist.',
    'product.backToCatalog': 'Back to Catalog',
    'product.season': 'Season',
    'product.selectSize': 'Select Size',
    'product.customizationOptions': 'Customization Options',
    'product.addLeaguePatches': 'Add League Patches',
    'product.patchesDesc': 'Official league patches for both sleeves',
    'product.addNameNumber': 'Add Player Name & Number',
    'product.nameNumberDesc': 'Official name and number printing on the back',
    'product.playerName': 'Player Name',
    'product.enterPlayerName': 'Enter player name',
    'product.number': 'Number',
    'product.addToCart': 'Add to Cart',
    'product.viewCart': 'View Cart',
    'product.paypalCheckout': 'Quick Checkout with PayPal',
    'product.freeShipping': 'Free shipping on orders over $100',
    'product.authentic': 'Authentic official licensed product',
    'product.securePayment': 'Secure payment with PayPal',

    // Auth
    'auth.login.title': 'Login',
    'auth.login.subtitle': 'Sign in to your account to continue',
    'auth.login.email': 'Email',
    'auth.login.password': 'Password',
    'auth.login.submit': 'Sign in',
    'auth.login.noAccount': 'Don\'t have an account?',
    'auth.login.createAccount': 'Create an account',

    'auth.register.title': 'Create Account',
    'auth.register.subtitle': 'Join us to access all our features',
    'auth.register.firstName': 'First Name',
    'auth.register.lastName': 'Last Name',
    'auth.register.email': 'Email',
    'auth.register.password': 'Password',
    'auth.register.submit': 'Create my account',
    'auth.register.hasAccount': 'Already have an account?',
    'auth.register.login': 'Sign in',

    // New Auth translations
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.loginDescription': 'Sign in to your account',
    'auth.registerDescription': 'Create your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.firstNamePlaceholder': 'Enter your first name',
    'auth.lastNamePlaceholder': 'Enter your last name',
    'auth.loggingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.loginError': 'Invalid email or password',
    'auth.registerError': 'Registration failed. Please try again.',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.acceptTermsRequired': 'Please accept the terms of service',
    'auth.acceptTerms': 'I accept the',
    'auth.termsOfService': 'Terms of Service',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.createAccount': 'Create account',
    'auth.continueWithFacebook': 'Continue with Facebook',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.orContinueWith': 'or continue with',
    'auth.facebookError': 'Facebook login failed. Please try again.',
    'auth.googleError': 'Google login failed. Please try again.',

    // User Menu
    'user.menu.orders': 'Order History',
    'user.menu.settings': 'Account Settings',
    'user.menu.logout': 'Sign Out',
    'user.menu.login': 'Sign In',
    'user.menu.register': 'Create Account',

    // Common
    'common.shopNow': 'Shop Now',
    'common.exploreCollection': 'Explore Collection',
    'common.newest': 'Newest',
    'common.priceLowToHigh': 'Price: Low to High',
    'common.priceHighToLow': 'Price: High to Low',
    'common.sortBy': 'Sort by:',
    'common.products': 'products',
    'common.product': 'product',
    'common.available': 'available',
    'common.premiumQuality': 'Premium Quality',
    'common.authenticProducts': 'Authentic Products',
    'common.updatedDaily': 'Updated Daily',
    'common.featured': 'Featured',
    'common.new': 'NEW',
    'common.accessories': 'Accessories',
    'common.equipment': 'Equipment',
    'common.premiumSelection': 'Premium Selection',
    'common.oneSize': 'One Size',
    'common.filters': 'Filters',
    'common.active': 'Active',
    'common.refineSearch': 'Refine your search',
    'common.category': 'Category',
    'common.allCategories': 'All Categories',
    'common.brand': 'Brand',
    'common.allBrands': 'All Brands',
    'common.clear': 'Clear',
    'common.scrollToExplore': 'Scroll to explore',
    'common.clearFilters': 'Clear filters',
    'common.clearAllFilters': 'Clear All Filters',
    'common.newestFirst': 'Newest First',

    // Homepage specific
    'home.wearYour': 'Wear Your',
    'home.passion': 'Passion',
    'home.premiumFootballGear': 'Premium Football Gear',
    'home.authenticShirts': 'Authentic football shirts from the world\'s greatest clubs and nations.',
    'home.premiumQualityWorldwide': 'Premium quality. Worldwide shipping.',
    'home.newArrivalsBtn': 'New Arrivals',
    'home.hundredPercent': '100% Authentic',
    'home.thousandProducts': '1000+ Products',
    'home.topBrands': 'Top Brands',
    'home.exploreCollection': 'Explore Collection',
    'home.moreThanShirts': 'More Than Just Shirts',
    'home.completeCollection': 'Complete your football collection',
    'home.officialClubScarves': 'Official club & match scarves',
    'home.officialTournamentBalls': 'Official tournament balls',
    'home.handPicked': 'Hand-picked selections from the world\'s most iconic clubs',
    'home.freshDrops': 'Fresh drops from the world\'s top brands',
    'home.wearPassionDescription': 'Wear Your Passion. Live Your Game.',
    'home.moreThanShirtQuote': '"More Than Just a Shirt - It\'s Your Identity"',
    'home.passionDescription': 'A football shirt isn\'t just fabric and colors. It\'s the roar of the stadium, the joy of victory, the pride of your club.',
    'home.passionExtended': 'Whether you\'re at the match, on the street, or with friends, wearing your team\'s colors connects you to millions of fans worldwide.',
    'home.vintageClassics': 'From vintage classics that tell legendary stories to modern masterpieces worn by today\'s heroes, each shirt carries the spirit of the beautiful game. Express your loyalty, celebrate your heritage, and show the world which side you\'re on. Because football is more than a sport – it\'s a way of life.',

    // New Arrivals Page
    'newArrivals.title': 'Fresh Arrivals',
    'newArrivals.subtitle': 'Latest Football Shirts & Gear',
    'newArrivals.description': 'Discover the newest additions to our collection. From the latest season jerseys to exclusive retro designs.',
    'newArrivals.hotNew': 'HOT & NEW',
    'newArrivals.allArrivals': 'All New Arrivals',
    'newArrivals.firstToKnow': 'Always First to Know',
    'newArrivals.dailyUpdates': 'We update our collection daily with the latest releases from top brands.',
    'newArrivals.latestKits': 'From current season kits to exclusive retro editions, you\'ll find the newest football shirts and gear right here.',
    'newArrivals.limitedEditions': 'Don\'t miss out on limited editions and special releases!',
    'newArrivals.lightningFast': 'Lightning Fast',
    'newArrivals.addedHours': 'New products added within hours of release',
    'newArrivals.premiumQuality': 'Premium Quality',
    'newArrivals.onlyAuthentic': 'Only authentic, official merchandise',
    'newArrivals.exclusiveAccess': 'Exclusive Access',
    'newArrivals.limitedEditionsExclusive': 'Limited editions you won\'t find elsewhere',

    // Scarves Page
    'scarves.title': 'Football Scarves Collection',
    'scarves.description': 'Show your colors with our collection of official club and match scarves. From classic designs to limited edition commemorative pieces.',
    'scarves.allScarves': 'All Scarves',
    'scarves.scarf': 'scarf',
    'scarves.scarves': 'scarves',
    'scarves.noScarves': 'No scarves found.',
    'scarves.whyCollect': 'Why Collect Football Scarves?',
    'scarves.symbolsLoyalty': 'Football scarves are more than just accessories - they\'re symbols of loyalty, passion, and unforgettable moments.',
    'scarves.connectsFans': 'Whether you\'re at the stadium, watching from home, or simply showing your support, a scarf connects you to your club and fellow fans.',
    'scarves.collectionIncludes': 'Our collection includes official club scarves, limited edition match scarves, and commemorative designs from historic fixtures.',
    'scarves.premiumMaterials': 'Each piece is crafted with premium materials and authentic club details.',

    // Balls Page
    'balls.title': 'Official Match Balls',
    'balls.ballsCollection': 'Balls Collection',
    'balls.description': 'Own a piece of football history with our collection of official match balls from the world\'s greatest tournaments and competitions.',
    'balls.allMatchBalls': 'All Match Balls',
    'balls.ball': 'ball',
    'balls.balls': 'balls',
    'balls.noBalls': 'No balls found.',
    'balls.collectHistory': 'Collect Football History',
    'balls.everyMoment': 'Every great moment in football starts with the ball.',
    'balls.legendaryTournaments': 'Our collection features official match balls from legendary tournaments - from World Cups and European Championships to Champions League finals and beyond.',
    'balls.notJustBalls': 'These aren\'t just balls - they\'re replicas of the exact designs used in historic matches.',
    'balls.perfectFor': 'Perfect for collectors, display pieces, or even for playing with the same quality the professionals use.',
    'balls.authenticBranding': 'Each ball comes with authentic tournament branding and premium construction.',
    'balls.collectorsItems': 'Collector\'s Items',

    // Bags Page
    'bags.title': 'Football Bags &',
    'bags.accessories': 'Accessories',
    'bags.description': 'Premium bags, waistpacks, and crossbody bags from top brands. Carry your gear in style.',
    'bags.allBags': 'All Bags & Accessories',
    'bags.noBags': 'No bags found.',
    'bags.gearUpStyle': 'Gear Up in Style',
    'bags.premiumBrands': 'Our collection features premium bags and accessories from Nike, Adidas, The North Face, and Under Armour.',
    'bags.needCompact': 'Whether you need a compact waistpack for match day, a crossbody bag for daily essentials, or a spacious tote for training gear, we\'ve got you covered.',
    'bags.functionality': 'Each bag combines functionality with style, featuring durable materials, smart organization, and iconic brand designs.',
    'bags.perfectFor': 'Perfect for athletes, fans, and anyone who values quality accessories.',
    'bags.premiumBrandsShort': 'Premium Brands',

  },
  fr: {
    // Top Banner
    'banner.worldwideShipping': '🌍 Livraison Internationale Disponible',
    'banner.authenticProducts': '✓ Produits 100% Authentiques',
    'banner.freeShipping': '📦 Livraison Gratuite dès 100€',

    // Navbar
    'nav.home': 'Accueil',
    'nav.newArrivals': 'Nouveautés',
    'nav.shirts': 'Maillots',
    'nav.clubs': 'Clubs',
    'nav.nationalTeams': 'Sélection nationales',
    'nav.scarves': 'Écharpes',
    'nav.balls': 'Ballons',
    'nav.bags': 'Sacs',
    'nav.promotion': 'Promotion',
    'nav.namesetPatches': 'Nameset & patches',
    'nav.searchPlaceholder': 'Rechercher des maillots...',
    'nav.accessories': 'Accessoires',
    'nav.equipment': 'Équipement',
    
    // Home page
    'home.hero.title': 'Maillots de Football Officiels',
    'home.hero.subtitle': 'Maillots authentiques de vos équipes et nations préférées. Qualité premium avec expédition mondiale.',
    'home.hero.shopNow': 'Acheter Maintenant',
    'home.hero.nationalTeams': 'Équipes Nationales',
    'home.newArrivals': 'Nouveautés',
    'home.new': 'Nouveau',
    'home.viewAllNew': 'Voir Toutes les Nouveautés',
    'home.shopByLeague': 'Acheter par Championnat',
    'home.featuredJerseys': 'Maillots Vedettes',
    'home.viewAllProducts': 'Voir Tous les Produits',
    'home.newsletter.title': 'Rejoignez notre Newsletter',
    'home.newsletter.subtitle': 'Abonnez-vous pour recevoir des offres spéciales, des cadeaux gratuits et des notifications de nouveautés.',
    'home.newsletter.placeholder': 'Votre adresse email',
    'home.newsletter.subscribe': 'S\'abonner',
    
    // Categories
    'category.nationalTeams': 'Équipes Nationales',
    'category.premierLeague': 'Premier League',
    'category.laLiga': 'La Liga',
    'category.serieA': 'Serie A',
    'category.bundesliga': 'Bundesliga',
    'category.ligue1': 'Ligue 1',
    
    // Catalog
    'catalog.filters': 'Filtres',
    'catalog.clearAll': 'Tout Effacer',
    'catalog.categories': 'Catégories',
    'catalog.sort': 'Trier par',
    'catalog.sort.newest': 'Plus récent',
    'catalog.sort.oldest': 'Plus ancien',
    'catalog.sort.priceAsc': 'Prix croissant',
    'catalog.sort.priceDesc': 'Prix décroissant',
    'catalog.sort.seasonDesc': 'Saison: Plus récente à plus ancienne',
    'catalog.sort.seasonAsc': 'Saison: Plus ancienne à plus récente',
    'catalog.price': 'Fourchette de prix',
    'catalog.price.min': 'Prix minimum',
    'catalog.price.max': 'Prix maximum',
    'catalog.brand': 'Marque',
    'catalog.competition': 'Compétition',
    'catalog.kitType': 'Type de maillot',
    'catalog.condition': 'État',
    'catalog.customization': 'Personnalisation',
    'catalog.customization.all': 'Tous les articles',
    'catalog.customization.withNameset': 'Avec flocage',
    'catalog.customization.withoutNameset': 'Sans flocage',
    'catalog.format': 'Format du maillot',
    'catalog.format.all': 'Tous les formats',
    'catalog.format.stadium': 'Version Stadium',
    'catalog.format.playerIssue': 'Version Pro',
    'catalog.format.proStock': 'Stock Pro',
    'catalog.format.matchWorn': 'Porté en match',
    'catalog.format.matchPrepared': 'Préparé pour match',
    'catalog.size': 'Taille',
    'catalog.applyFilters': 'Appliquer les Filtres',
    'catalog.allProducts': 'Tous les Produits',
    'catalog.searchResults': 'Résultats de recherche pour',
    'catalog.productsFound': 'produits trouvés',
    'catalog.productFound': 'produit trouvé',
    'catalog.hideFilters': 'Masquer les Filtres',
    'catalog.showFilters': 'Afficher les Filtres',
    'catalog.searchPlaceholder': 'Rechercher des produits...',
    'catalog.search': 'Rechercher',
    'catalog.noProducts': 'Aucun produit trouvé',
    'catalog.noProductsDesc': 'Essayez d\'ajuster votre recherche ou filtre pour trouver ce que vous cherchez.',
    'catalog.clearFilters': 'Effacer les Filtres',
    
    // Social
    'social.whatsapp': 'Contactez-nous sur WhatsApp',
    'social.instagram': 'Suivez-nous sur Instagram',

    // Payment
    'payment.acceptedMethods': 'Moyens de paiement acceptés',

    // Product card
    'product.customizable': 'Personnalisable',
    'product.viewDetails': 'Voir les Détails',

    // Product detail
    'product.notFound': 'Produit non trouvé',
    'product.notFoundDesc': 'Désolé, le produit que vous recherchez n\'existe pas.',
    'product.backToCatalog': 'Retour au catalogue',
    'product.season': 'Saison',
    'product.selectSize': 'Sélectionnez la taille',
    'product.customizationOptions': 'Options de personnalisation',
    'product.addLeaguePatches': 'Ajouter les écussons de la ligue',
    'product.patchesDesc': 'Écussons officiels de la ligue pour les deux manches',
    'product.addNameNumber': 'Ajouter nom et numéro du joueur',
    'product.nameNumberDesc': 'Flocage officiel du nom et du numéro au dos',
    'product.playerName': 'Nom du joueur',
    'product.enterPlayerName': 'Entrez le nom du joueur',
    'product.number': 'Numéro',
    'product.addToCart': 'Ajouter au panier',
    'product.viewCart': 'Voir le panier',
    'product.paypalCheckout': 'Paiement rapide avec PayPal',
    'product.freeShipping': 'Livraison gratuite pour les commandes de plus de 100€',
    'product.authentic': 'Produit officiel authentique',
    'product.securePayment': 'Paiement sécurisé avec PayPal',

    // Auth
    'auth.login.title': 'Connexion',
    'auth.login.subtitle': 'Connectez-vous à votre compte pour continuer',
    'auth.login.email': 'Email',
    'auth.login.password': 'Mot de passe',
    'auth.login.submit': 'Se connecter',
    'auth.login.noAccount': 'Pas encore de compte ?',
    'auth.login.createAccount': 'Créer un compte',

    'auth.register.title': 'Créer un compte',
    'auth.register.subtitle': 'Rejoignez-nous pour accéder à toutes nos fonctionnalités',
    'auth.register.firstName': 'Prénom',
    'auth.register.lastName': 'Nom',
    'auth.register.email': 'Email',
    'auth.register.password': 'Mot de passe',
    'auth.register.submit': 'Créer mon compte',
    'auth.register.hasAccount': 'Déjà un compte ?',
    'auth.register.login': 'Se connecter',

    // User Menu
    'user.menu.orders': 'Historique des commandes',
    'user.menu.settings': 'Paramètres du compte',
    'user.menu.logout': 'Se déconnecter',
    'user.menu.login': 'Se connecter',
    'user.menu.register': 'Créer un compte',

    // Common
    'common.shopNow': 'Acheter Maintenant',
    'common.exploreCollection': 'Explorer la Collection',
    'common.newest': 'Plus Récent',
    'common.priceLowToHigh': 'Prix: Croissant',
    'common.priceHighToLow': 'Prix: Décroissant',
    'common.sortBy': 'Trier par:',
    'common.products': 'produits',
    'common.product': 'produit',
    'common.available': 'disponible',
    'common.premiumQuality': 'Qualité Premium',
    'common.authenticProducts': 'Produits Authentiques',
    'common.updatedDaily': 'Mis à Jour Quotidiennement',
    'common.featured': 'En Vedette',
    'common.new': 'NOUVEAU',
    'common.accessories': 'Accessoires',
    'common.equipment': 'Équipement',
    'common.premiumSelection': 'Sélection Premium',
    'common.oneSize': 'Taille Unique',
    'common.filters': 'Filtres',
    'common.active': 'Actif',
    'common.refineSearch': 'Affinez votre recherche',
    'common.category': 'Catégorie',
    'common.allCategories': 'Toutes les Catégories',
    'common.brand': 'Marque',
    'common.allBrands': 'Toutes les Marques',
    'common.clear': 'Effacer',
    'common.scrollToExplore': 'Faites défiler pour explorer',
    'common.clearFilters': 'Effacer les filtres',
    'common.clearAllFilters': 'Effacer Tous les Filtres',
    'common.newestFirst': 'Plus Récent d\'Abord',

    // Homepage specific
    'home.wearYour': 'Portez Votre',
    'home.passion': 'Passion',
    'home.premiumFootballGear': 'Équipement de Football Premium',
    'home.authenticShirts': 'Maillots de football authentiques des plus grands clubs et nations du monde.',
    'home.premiumQualityWorldwide': 'Qualité premium. Expédition mondiale.',
    'home.newArrivalsBtn': 'Nouveautés',
    'home.hundredPercent': '100% Authentique',
    'home.thousandProducts': '1000+ Produits',
    'home.topBrands': 'Grandes Marques',
    'home.exploreCollection': 'Explorer la Collection',
    'home.moreThanShirts': 'Plus Que Des Maillots',
    'home.completeCollection': 'Complétez votre collection de football',
    'home.officialClubScarves': 'Écharpes officielles de clubs et de matchs',
    'home.officialTournamentBalls': 'Ballons de tournois officiels',
    'home.handPicked': 'Sélections triées des clubs les plus emblématiques du monde',
    'home.freshDrops': 'Nouveautés des plus grandes marques mondiales',
    'home.wearPassionDescription': 'Portez Votre Passion. Vivez Votre Jeu.',
    'home.moreThanShirtQuote': '"Plus Qu\'un Maillot - C\'est Votre Identité"',
    'home.passionDescription': 'Un maillot de football n\'est pas qu\'un tissu et des couleurs. C\'est le rugissement du stade, la joie de la victoire, la fierté de votre club.',
    'home.passionExtended': 'Que vous soyez au match, dans la rue ou avec des amis, porter les couleurs de votre équipe vous connecte à des millions de fans dans le monde.',
    'home.vintageClassics': 'Des classiques vintage qui racontent des histoires légendaires aux chefs-d\'œuvre modernes portés par les héros d\'aujourd\'hui, chaque maillot porte l\'esprit du beau jeu. Exprimez votre loyauté, célébrez votre héritage et montrez au monde de quel côté vous êtes. Parce que le football est plus qu\'un sport – c\'est un mode de vie.',

    // New Arrivals Page
    'newArrivals.title': 'Nouvelles Arrivées',
    'newArrivals.subtitle': 'Derniers Maillots et Équipements',
    'newArrivals.description': 'Découvrez les derniers ajouts à notre collection. Des maillots de la dernière saison aux designs rétro exclusifs.',
    'newArrivals.hotNew': 'CHAUD & NOUVEAU',
    'newArrivals.allArrivals': 'Toutes les Nouveautés',
    'newArrivals.firstToKnow': 'Toujours les Premiers Informés',
    'newArrivals.dailyUpdates': 'Nous mettons à jour notre collection quotidiennement avec les dernières sorties des grandes marques.',
    'newArrivals.latestKits': 'Des maillots de la saison en cours aux éditions rétro exclusives, vous trouverez ici les derniers maillots et équipements de football.',
    'newArrivals.limitedEditions': 'Ne manquez pas les éditions limitées et les sorties spéciales!',
    'newArrivals.lightningFast': 'Ultra Rapide',
    'newArrivals.addedHours': 'Nouveaux produits ajoutés quelques heures après leur sortie',
    'newArrivals.premiumQuality': 'Qualité Premium',
    'newArrivals.onlyAuthentic': 'Uniquement des produits officiels authentiques',
    'newArrivals.exclusiveAccess': 'Accès Exclusif',
    'newArrivals.limitedEditionsExclusive': 'Éditions limitées introuvables ailleurs',

    // Scarves Page
    'scarves.title': 'Collection d\'Écharpes de Football',
    'scarves.description': 'Affichez vos couleurs avec notre collection d\'écharpes officielles de clubs et de matchs. Des designs classiques aux pièces commémoratives en édition limitée.',
    'scarves.allScarves': 'Toutes les Écharpes',
    'scarves.scarf': 'écharpe',
    'scarves.scarves': 'écharpes',
    'scarves.noScarves': 'Aucune écharpe trouvée.',
    'scarves.whyCollect': 'Pourquoi Collectionner les Écharpes de Football?',
    'scarves.symbolsLoyalty': 'Les écharpes de football sont plus que de simples accessoires - ce sont des symboles de loyauté, de passion et de moments inoubliables.',
    'scarves.connectsFans': 'Que vous soyez au stade, en train de regarder depuis chez vous ou simplement en montrant votre soutien, une écharpe vous connecte à votre club et aux autres supporters.',
    'scarves.collectionIncludes': 'Notre collection comprend des écharpes officielles de clubs, des écharpes de matchs en édition limitée et des designs commémoratifs de rencontres historiques.',
    'scarves.premiumMaterials': 'Chaque pièce est fabriquée avec des matériaux premium et des détails authentiques du club.',

    // Balls Page
    'balls.title': 'Ballons de Match Officiels',
    'balls.ballsCollection': 'Collection de Ballons',
    'balls.description': 'Possédez un morceau d\'histoire du football avec notre collection de ballons de match officiels des plus grands tournois et compétitions du monde.',
    'balls.allMatchBalls': 'Tous les Ballons de Match',
    'balls.ball': 'ballon',
    'balls.balls': 'ballons',
    'balls.noBalls': 'Aucun ballon trouvé.',
    'balls.collectHistory': 'Collectionnez l\'Histoire du Football',
    'balls.everyMoment': 'Chaque grand moment du football commence avec le ballon.',
    'balls.legendaryTournaments': 'Notre collection présente des ballons de match officiels de tournois légendaires - des Coupes du Monde et Championnats d\'Europe aux finales de Ligue des Champions et au-delà.',
    'balls.notJustBalls': 'Ce ne sont pas que des ballons - ce sont des répliques exactes des designs utilisés lors de matchs historiques.',
    'balls.perfectFor': 'Parfaits pour les collectionneurs, les pièces d\'exposition ou même pour jouer avec la même qualité que les professionnels.',
    'balls.authenticBranding': 'Chaque ballon est livré avec le marquage authentique du tournoi et une construction premium.',
    'balls.collectorsItems': 'Articles de Collection',

    // Bags Page
    'bags.title': 'Sacs de Football &',
    'bags.accessories': 'Accessoires',
    'bags.description': 'Sacs premium, bananes et sacs bandoulière des grandes marques. Transportez votre équipement avec style.',
    'bags.allBags': 'Tous les Sacs & Accessoires',
    'bags.noBags': 'Aucun sac trouvé.',
    'bags.gearUpStyle': 'Équipez-vous avec Style',
    'bags.premiumBrands': 'Notre collection comprend des sacs et accessoires premium de Nike, Adidas, The North Face et Under Armour.',
    'bags.needCompact': 'Que vous ayez besoin d\'une banane compacte pour le jour du match, d\'un sac bandoulière pour vos essentiels quotidiens ou d\'un grand tote pour votre équipement d\'entraînement, nous avons ce qu\'il vous faut.',
    'bags.functionality': 'Chaque sac allie fonctionnalité et style, avec des matériaux durables, une organisation intelligente et des designs de marques iconiques.',
    'bags.perfectFor': 'Parfait pour les athlètes, les fans et tous ceux qui valorisent les accessoires de qualité.',
    'bags.premiumBrandsShort': 'Marques Premium',

  },
  es: {
    // Top Banner
    'banner.worldwideShipping': '🌍 Envío Mundial Disponible',
    'banner.authenticProducts': '✓ Productos 100% Auténticos',
    'banner.freeShipping': '📦 Envío Gratis en Pedidos Superiores a 100€',

    // Navbar
    'nav.home': 'Inicio',
    'nav.newArrivals': 'Novedades',
    'nav.shirts': 'Camisetas',
    'nav.clubs': 'Clubes',
    'nav.nationalTeams': 'Selecciones Nacionales',
    'nav.scarves': 'Bufandas',
    'nav.balls': 'Balones',
    'nav.bags': 'Bolsas',
    'nav.promotion': 'Promoción',
    'nav.namesetPatches': 'Nameset & Parches',
    'nav.searchPlaceholder': 'Buscar camisetas...',
    'nav.accessories': 'Accesorios',
    'nav.equipment': 'Equipamiento',
    
    // Home page
    'home.hero.title': 'Camisetas de Fútbol Oficiales',
    'home.hero.subtitle': 'Camisetas auténticas de tus equipos y naciones favoritas. Calidad premium con envío mundial.',
    'home.hero.shopNow': 'Comprar Ahora',
    'home.hero.nationalTeams': 'Selecciones Nacionales',
    'home.newArrivals': 'Novedades',
    'home.new': 'Nuevo',
    'home.viewAllNew': 'Ver Todas las Novedades',
    'home.shopByLeague': 'Comprar por Liga',
    'home.featuredJerseys': 'Camisetas Destacadas',
    'home.viewAllProducts': 'Ver Todos los Productos',
    'home.newsletter.title': 'Únete a nuestro Newsletter',
    'home.newsletter.subtitle': 'Suscríbete para recibir ofertas especiales, regalos gratuitos y notificaciones de novedades.',
    'home.newsletter.placeholder': 'Tu dirección de email',
    'home.newsletter.subscribe': 'Suscribirse',
    
    // Categories
    'category.nationalTeams': 'Selecciones Nacionales',
    'category.premierLeague': 'Premier League',
    'category.laLiga': 'La Liga',
    'category.serieA': 'Serie A',
    'category.bundesliga': 'Bundesliga',
    'category.ligue1': 'Ligue 1',
    
    // Catalog
    'catalog.filters': 'Filtros',
    'catalog.clearAll': 'Limpiar Todo',
    'catalog.categories': 'Categorías',
    'catalog.sort': 'Ordenar por',
    'catalog.sort.newest': 'Más reciente',
    'catalog.sort.oldest': 'Más antiguo',
    'catalog.sort.priceAsc': 'Precio: menor a mayor',
    'catalog.sort.priceDesc': 'Precio: mayor a menor',
    'catalog.sort.seasonDesc': 'Temporada: Más reciente a más antigua',
    'catalog.sort.seasonAsc': 'Temporada: Más antigua a más reciente',
    'catalog.price': 'Rango de precio',
    'catalog.price.min': 'Precio mínimo',
    'catalog.price.max': 'Precio máximo',
    'catalog.brand': 'Marca',
    'catalog.competition': 'Competición',
    'catalog.kitType': 'Tipo de camiseta',
    'catalog.condition': 'Estado',
    'catalog.customization': 'Personalización',
    'catalog.customization.all': 'Todos los artículos',
    'catalog.customization.withNameset': 'Con dorsal',
    'catalog.customization.withoutNameset': 'Sin dorsal',
    'catalog.format': 'Formato de camiseta',
    'catalog.format.all': 'Todos los formatos',
    'catalog.format.stadium': 'Versión Stadium',
    'catalog.format.playerIssue': 'Versión Pro',
    'catalog.format.proStock': 'Stock Pro',
    'catalog.format.matchWorn': 'Usada en partido',
    'catalog.format.matchPrepared': 'Preparada para partido',
    'catalog.size': 'Talla',
    'catalog.applyFilters': 'Aplicar Filtros',
    'catalog.allProducts': 'Todos los Productos',
    'catalog.searchResults': 'Resultados de búsqueda para',
    'catalog.productsFound': 'productos encontrados',
    'catalog.productFound': 'producto encontrado',
    'catalog.hideFilters': 'Ocultar Filtros',
    'catalog.showFilters': 'Mostrar Filtros',
    'catalog.searchPlaceholder': 'Buscar productos...',
    'catalog.search': 'Buscar',
    'catalog.noProducts': 'No se encontraron productos',
    'catalog.noProductsDesc': 'Intenta ajustar tu búsqueda o filtro para encontrar lo que buscas.',
    'catalog.clearFilters': 'Limpiar Filtros',
    
    // Social
    'social.whatsapp': 'Contáctanos en WhatsApp',
    'social.instagram': 'Síguenos en Instagram',

    // Payment
    'payment.acceptedMethods': 'Métodos de pago aceptados',

    // Product card
    'product.customizable': 'Personalizable',
    'product.viewDetails': 'Ver Detalles',

    // Product detail
    'product.notFound': 'Producto no encontrado',
    'product.notFoundDesc': 'Lo sentimos, el producto que buscas no existe.',
    'product.backToCatalog': 'Volver al catálogo',
    'product.season': 'Temporada',
    'product.selectSize': 'Seleccionar talla',
    'product.customizationOptions': 'Opciones de personalización',
    'product.addLeaguePatches': 'Añadir parches de la liga',
    'product.patchesDesc': 'Parches oficiales de la liga para ambas mangas',
    'product.addNameNumber': 'Añadir nombre y número de jugador',
    'product.nameNumberDesc': 'Impresión oficial de nombre y número en la espalda',
    'product.playerName': 'Nombre del jugador',
    'product.enterPlayerName': 'Introduce el nombre del jugador',
    'product.number': 'Número',
    'product.addToCart': 'Añadir al carrito',
    'product.viewCart': 'Ver carrito',
    'product.paypalCheckout': 'Pago rápido con PayPal',
    'product.freeShipping': 'Envío gratis en pedidos superiores a 100€',
    'product.authentic': 'Producto oficial auténtico',
    'product.securePayment': 'Pago seguro con PayPal',

    // Auth
    'auth.login.title': 'Iniciar Sesión',
    'auth.login.subtitle': 'Inicia sesión en tu cuenta para continuar',
    'auth.login.email': 'Correo electrónico',
    'auth.login.password': 'Contraseña',
    'auth.login.submit': 'Iniciar sesión',
    'auth.login.noAccount': '¿No tienes una cuenta?',
    'auth.login.createAccount': 'Crear una cuenta',

    'auth.register.title': 'Crear Cuenta',
    'auth.register.subtitle': 'Únete para acceder a todas nuestras funciones',
    'auth.register.firstName': 'Nombre',
    'auth.register.lastName': 'Apellido',
    'auth.register.email': 'Correo electrónico',
    'auth.register.password': 'Contraseña',
    'auth.register.submit': 'Crear mi cuenta',
    'auth.register.hasAccount': '¿Ya tienes una cuenta?',
    'auth.register.login': 'Iniciar sesión',

    // User Menu
    'user.menu.orders': 'Historial de pedidos',
    'user.menu.settings': 'Configuración de cuenta',
    'user.menu.logout': 'Cerrar sesión',
    'user.menu.login': 'Iniciar sesión',
    'user.menu.register': 'Crear cuenta',

    // Common
    'common.shopNow': 'Comprar Ahora',
    'common.exploreCollection': 'Explorar Colección',
    'common.newest': 'Más Reciente',
    'common.priceLowToHigh': 'Precio: Menor a Mayor',
    'common.priceHighToLow': 'Precio: Mayor a Menor',
    'common.sortBy': 'Ordenar por:',
    'common.products': 'productos',
    'common.product': 'producto',
    'common.available': 'disponible',
    'common.premiumQuality': 'Calidad Premium',
    'common.authenticProducts': 'Productos Auténticos',
    'common.updatedDaily': 'Actualizado Diariamente',
    'common.featured': 'Destacado',
    'common.new': 'NUEVO',
    'common.accessories': 'Accesorios',
    'common.equipment': 'Equipamiento',
    'common.premiumSelection': 'Selección Premium',
    'common.oneSize': 'Talla Única',
    'common.filters': 'Filtros',
    'common.active': 'Activo',
    'common.refineSearch': 'Refina tu búsqueda',
    'common.category': 'Categoría',
    'common.allCategories': 'Todas las Categorías',
    'common.brand': 'Marca',
    'common.allBrands': 'Todas las Marcas',
    'common.clear': 'Limpiar',
    'common.scrollToExplore': 'Desplázate para explorar',
    'common.clearFilters': 'Limpiar filtros',
    'common.clearAllFilters': 'Limpiar Todos los Filtros',
    'common.newestFirst': 'Más Reciente Primero',

    // Homepage specific
    'home.wearYour': 'Viste Tu',
    'home.passion': 'Pasión',
    'home.premiumFootballGear': 'Equipamiento de Fútbol Premium',
    'home.authenticShirts': 'Camisetas de fútbol auténticas de los mejores clubes y naciones del mundo.',
    'home.premiumQualityWorldwide': 'Calidad premium. Envío mundial.',
    'home.newArrivalsBtn': 'Novedades',
    'home.hundredPercent': '100% Auténtico',
    'home.thousandProducts': '1000+ Productos',
    'home.topBrands': 'Mejores Marcas',
    'home.exploreCollection': 'Explorar Colección',
    'home.moreThanShirts': 'Más Que Solo Camisetas',
    'home.completeCollection': 'Completa tu colección de fútbol',
    'home.officialClubScarves': 'Bufandas oficiales de clubes y partidos',
    'home.officialTournamentBalls': 'Balones de torneos oficiales',
    'home.handPicked': 'Selecciones escogidas de los clubes más icónicos del mundo',
    'home.freshDrops': 'Novedades de las mejores marcas del mundo',
    'home.wearPassionDescription': 'Viste Tu Pasión. Vive Tu Juego.',
    'home.moreThanShirtQuote': '"Más Que Una Camiseta - Es Tu Identidad"',
    'home.passionDescription': 'Una camiseta de fútbol no es solo tela y colores. Es el rugido del estadio, la alegría de la victoria, el orgullo de tu club.',
    'home.passionExtended': 'Ya sea en el partido, en la calle o con amigos, usar los colores de tu equipo te conecta con millones de aficionados en todo el mundo.',
    'home.vintageClassics': 'Desde clásicos vintage que cuentan historias legendarias hasta obras maestras modernas usadas por los héroes de hoy, cada camiseta lleva el espíritu del hermoso juego. Expresa tu lealtad, celebra tu herencia y muéstrale al mundo de qué lado estás. Porque el fútbol es más que un deporte: es un estilo de vida.',

    // New Arrivals Page
    'newArrivals.title': 'Nuevas Llegadas',
    'newArrivals.subtitle': 'Últimas Camisetas y Equipamiento',
    'newArrivals.description': 'Descubre las últimas incorporaciones a nuestra colección. Desde camisetas de la última temporada hasta diseños retro exclusivos.',
    'newArrivals.hotNew': 'CALIENTE Y NUEVO',
    'newArrivals.allArrivals': 'Todas las Novedades',
    'newArrivals.firstToKnow': 'Siempre los Primeros en Saberlo',
    'newArrivals.dailyUpdates': 'Actualizamos nuestra colección diariamente con los últimos lanzamientos de las mejores marcas.',
    'newArrivals.latestKits': 'Desde camisetas de la temporada actual hasta ediciones retro exclusivas, encontrarás aquí las camisetas y equipamiento de fútbol más nuevos.',
    'newArrivals.limitedEditions': '¡No te pierdas las ediciones limitadas y lanzamientos especiales!',
    'newArrivals.lightningFast': 'Súper Rápido',
    'newArrivals.addedHours': 'Nuevos productos agregados horas después de su lanzamiento',
    'newArrivals.premiumQuality': 'Calidad Premium',
    'newArrivals.onlyAuthentic': 'Solo productos oficiales auténticos',
    'newArrivals.exclusiveAccess': 'Acceso Exclusivo',
    'newArrivals.limitedEditionsExclusive': 'Ediciones limitadas que no encontrarás en otro lugar',

    // Scarves Page
    'scarves.title': 'Colección de Bufandas de Fútbol',
    'scarves.description': 'Muestra tus colores con nuestra colección de bufandas oficiales de clubes y partidos. Desde diseños clásicos hasta piezas conmemorativas de edición limitada.',
    'scarves.allScarves': 'Todas las Bufandas',
    'scarves.scarf': 'bufanda',
    'scarves.scarves': 'bufandas',
    'scarves.noScarves': 'No se encontraron bufandas.',
    'scarves.whyCollect': '¿Por Qué Coleccionar Bufandas de Fútbol?',
    'scarves.symbolsLoyalty': 'Las bufandas de fútbol son más que simples accesorios: son símbolos de lealtad, pasión y momentos inolvidables.',
    'scarves.connectsFans': 'Ya sea en el estadio, viendo desde casa o simplemente mostrando tu apoyo, una bufanda te conecta con tu club y otros aficionados.',
    'scarves.collectionIncludes': 'Nuestra colección incluye bufandas oficiales de clubes, bufandas de partidos de edición limitada y diseños conmemorativos de encuentros históricos.',
    'scarves.premiumMaterials': 'Cada pieza está elaborada con materiales premium y detalles auténticos del club.',

    // Balls Page
    'balls.title': 'Balones de Partido Oficiales',
    'balls.ballsCollection': 'Colección de Balones',
    'balls.description': 'Posee un pedazo de historia del fútbol con nuestra colección de balones de partido oficiales de los torneos y competiciones más grandes del mundo.',
    'balls.allMatchBalls': 'Todos los Balones de Partido',
    'balls.ball': 'balón',
    'balls.balls': 'balones',
    'balls.noBalls': 'No se encontraron balones.',
    'balls.collectHistory': 'Colecciona Historia del Fútbol',
    'balls.everyMoment': 'Cada gran momento en el fútbol comienza con el balón.',
    'balls.legendaryTournaments': 'Nuestra colección presenta balones de partido oficiales de torneos legendarios: desde Mundiales y Eurocopas hasta finales de Champions League y más.',
    'balls.notJustBalls': 'No son solo balones: son réplicas exactas de los diseños usados en partidos históricos.',
    'balls.perfectFor': 'Perfectos para coleccionistas, piezas de exhibición o incluso para jugar con la misma calidad que usan los profesionales.',
    'balls.authenticBranding': 'Cada balón viene con el branding auténtico del torneo y construcción premium.',
    'balls.collectorsItems': 'Artículos de Colección',

    // Bags Page
    'bags.title': 'Bolsas de Fútbol y',
    'bags.accessories': 'Accesorios',
    'bags.description': 'Bolsas premium, riñoneras y bolsos cruzados de las mejores marcas. Lleva tu equipo con estilo.',
    'bags.allBags': 'Todas las Bolsas y Accesorios',
    'bags.noBags': 'No se encontraron bolsas.',
    'bags.gearUpStyle': 'Equípate con Estilo',
    'bags.premiumBrands': 'Nuestra colección presenta bolsas y accesorios premium de Nike, Adidas, The North Face y Under Armour.',
    'bags.needCompact': 'Ya sea que necesites una riñonera compacta para el día del partido, un bolso cruzado para tus esenciales diarios o un tote espacioso para tu equipo de entrenamiento, te tenemos cubierto.',
    'bags.functionality': 'Cada bolsa combina funcionalidad con estilo, con materiales duraderos, organización inteligente y diseños de marcas icónicas.',
    'bags.perfectFor': 'Perfecto para atletas, aficionados y cualquiera que valore accesorios de calidad.',
    'bags.premiumBrandsShort': 'Marcas Premium',

  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export { useLanguage };